title: PRL Software Projects
description: Phases Research Lab Software Projects
theme: just-the-docs
color_scheme: wider

url: https://phasesresearchlab.github.io/SoftwareProjects/

favicon_ico: "/assets/PRL_logo.ico"

search_enabled: true
heading_anchors: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

aux_links:
  Repository: "https://github.com/PhasesResearchLab/SoftwareProjects"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/PhasesResearchLab/SoftwareProjects" 
gh_edit_branch: "main"
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately