name: Get PDF&HTML
on:
  push:
    paths:
      - README.md

jobs:
  convert:
    runs-on: ubuntu-latest
    name: Get PDF&HTML
    steps:
      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: README.md
          output_dir: renders
          build_html: true
          build_pdf: true
          table_of_contents: true
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: README.pdf
      - name: Upload HTML
        uses: actions/upload-artifact@v1
        with:
          name: html
          path: renders/README.html
        
            
